const initialState = {
  categories: [
    { id: 'tenis', name: 'Tenis' },
    { id: 'squash', name: 'Squash' },
    { id: 'padel', name: 'Padel' },
    { id: 'badminton', name: 'Badminton' },
    { id: 'tableTenis', name: 'Table Tenis' },
  ],
  products: [
    {
      id: 'tenis-racket-1',
      name: 'Pro Tenis Racket 1',
      category: 'tenis',
      manufacturer: 'babolat',
      price: 1038,
      oldPrice: null,
      age: 'adult',
      color: ['white', 'green'],
      stars: 3,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/tenis/tenis-racket-1.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tenis-racket-2',
      name: 'Light Tenis Racket 2',
      category: 'tenis',
      manufacturer: 'head',
      price: 692,
      oldPrice: null,
      age: 'child',
      color: ['red'],
      stars: 2,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/tenis/tenis-racket-2.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tenis-racket-3',
      name: 'Heavy Tenis Racket 3',
      category: 'tenis',
      manufacturer: 'wilson',
      price: 1189,
      oldPrice: null,
      age: 'adult',
      color: ['blue'],
      stars: 3,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/tenis/tenis-racket-3.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tenis-racket-4',
      name: 'Amazing Tenis Racket 4',
      category: 'tenis',
      manufacturer: 'yonex',
      price: 1305,
      oldPrice: null,
      age: 'adult',
      color: ['black', 'green'],
      stars: 5,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: true,
      saleOff: false,
      source: '/images/racket/tenis/tenis-racket-4.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tenis-racket-5',
      name: 'Pro Tenis Racket 5',
      category: 'tenis',
      manufacturer: 'prince',
      price: 940,
      oldPrice: null,
      age: 'adult',
      color: ['white'],
      stars: 4,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/tenis/tenis-racket-5.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tenis-racket-6',
      name: 'Light Tenis Racket 6',
      category: 'tenis',
      manufacturer: 'prince',
      price: 1128,
      oldPrice: null,
      age: 'adult',
      color: ['black', 'red'],
      stars: 3,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/tenis/tenis-racket-6.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tenis-racket-7',
      name: 'Pro Tenis Racket 7',
      category: 'tenis',
      manufacturer: 'head',
      price: 1047,
      oldPrice: 1368,
      age: 'child',
      color: ['blue'],
      stars: 2,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: true,
      source: '/images/racket/tenis/tenis-racket-7.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tenis-racket-8',
      name: 'Pro Tenis Racket 8',
      category: 'tenis',
      manufacturer: 'yonex',
      price: 1331,
      oldPrice: null,
      age: 'child',
      color: ['white'],
      stars: 5,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/tenis/tenis-racket-8.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tenis-racket-9',
      name: 'Heavy Tenis Racket 9',
      category: 'tenis',
      manufacturer: 'wilson',
      price: 1258,
      oldPrice: null,
      age: 'adult',
      color: ['black'],
      stars: 1,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/tenis/tenis-racket-9.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tenis-racket-10',
      name: 'Amateur Tenis Racket 10',
      category: 'tenis',
      manufacturer: 'babolat',
      price: 1075,
      oldPrice: 1730,
      age: 'child',
      color: ['green'],
      stars: 2,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: true,
      source: '/images/racket/tenis/tenis-racket-10.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tenis-racket-11',
      name: 'Pro Tenis Racket 11',
      category: 'tenis',
      manufacturer: 'wilson',
      price: 800,
      oldPrice: null,
      age: 'adult',
      color: ['red', 'white'],
      stars: 2,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/tenis/tenis-racket-11.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tenis-racket-12',
      name: 'Heavy Tenis Racket 12',
      category: 'tenis',
      manufacturer: 'yonex',
      price: 620,
      oldPrice: null,
      age: 'child',
      color: ['blue'],
      stars: 4,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/tenis/tenis-racket-12.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tenis-racket-13',
      name: 'Light Tenis Racket 13',
      category: 'tenis',
      manufacturer: 'head',
      price: 1340,
      oldPrice: 1630,
      age: 'adult',
      color: ['green'],
      stars: 5,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: true,
      topSeller: false,
      saleOff: true,
      source: '/images/racket/tenis/tenis-racket-13.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tenis-racket-14',
      name: 'Amazing Tenis Racket 14',
      category: 'tenis',
      manufacturer: 'babolat',
      price: 620,
      oldPrice: null,
      age: 'adult',
      color: ['yellow'],
      stars: 3,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/tenis/tenis-racket-14.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tenis-racket-15',
      name: 'Pro Tenis Racket 15',
      category: 'tenis',
      manufacturer: 'prince',
      price: 1200,
      oldPrice: 1480,
      age: 'adult',
      color: ['white', 'blue'],
      stars: 4,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: true,
      source: '/images/racket/tenis/tenis-racket-15.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tenis-racket-16',
      name: 'Pro Tenis Racket 16',
      category: 'tenis',
      manufacturer: 'wilson',
      price: 840,
      oldPrice: 1330,
      age: 'adult',
      color: ['green'],
      stars: 3,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: true,
      source: '/images/racket/tenis/tenis-racket-16.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tenis-racket-17',
      name: 'Heavy Tenis Racket 17',
      category: 'tenis',
      manufacturer: 'yonex',
      price: 750,
      oldPrice: null,
      age: 'adult',
      color: ['blue'],
      stars: 4,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/tenis/tenis-racket-17.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tenis-racket-18',
      name: 'Light Tenis Racket 18',
      category: 'tenis',
      manufacturer: 'babolat',
      price: 1300,
      oldPrice: null,
      age: 'adult',
      color: ['black', 'red'],
      stars: 5,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: true,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/tenis/tenis-racket-18.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tenis-racket-19',
      name: 'Pro Tenis Racket 19',
      category: 'tenis',
      manufacturer: 'wilson',
      price: 1230,
      oldPrice: null,
      age: 'adult',
      color: ['white'],
      stars: 4,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/tenis/tenis-racket-19.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tenis-racket-20',
      name: 'Pro Tenis Racket 20',
      category: 'tenis',
      manufacturer: 'yonex',
      price: 1260,
      oldPrice: null,
      age: 'adult',
      color: ['blue', 'green'],
      stars: 5,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: true,
      saleOff: false,
      source: '/images/racket/tenis/tenis-racket-20.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tenis-racket-21',
      name: 'Light Tenis Racket 21',
      category: 'tenis',
      manufacturer: 'prince',
      price: 803,
      oldPrice: null,
      age: 'child',
      color: ['blue', 'red'],
      stars: 3,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/tenis/tenis-racket-21.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tenis-racket-22',
      name: 'Amazing Tenis Racket 22',
      category: 'tenis',
      manufacturer: 'wilson',
      price: 1115,
      oldPrice: 1599,
      age: 'adult',
      color: ['black', 'green'],
      stars: 2,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: true,
      source: '/images/racket/tenis/tenis-racket-22.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tenis-racket-23',
      name: 'Light Tenis Racket 23',
      category: 'tenis',
      manufacturer: 'head',
      price: 1032,
      oldPrice: null,
      age: 'adult',
      color: ['green', 'white'],
      stars: 5,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/tenis/tenis-racket-23.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tenis-racket-24',
      name: 'Pro Tenis Racket 24',
      category: 'tenis',
      manufacturer: 'yonex',
      price: 1005,
      oldPrice: null,
      age: 'child',
      color: ['white'],
      stars: 4,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/tenis/tenis-racket-24.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tenis-racket-25',
      name: 'Heavy Tenis Racket 25',
      category: 'tenis',
      manufacturer: 'prince',
      price: 1074,
      oldPrice: null,
      age: 'adult',
      color: ['blue'],
      stars: 1,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/tenis/tenis-racket-25.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'squash-racket-1',
      name: 'Pro Squash Racket 1',
      category: 'squash',
      manufacturer: 'babolat',
      price: 944,
      oldPrice: null,
      age: 'adult',
      color: ['black', 'white'],
      stars: 4,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/squash/squash-racket-1.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'squash-racket-2',
      name: 'Amateur Squash Racket 2',
      category: 'squash',
      manufacturer: 'wilson',
      price: 1083,
      oldPrice: null,
      age: 'adult',
      color: ['green'],
      stars: 2,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/squash/squash-racket-2.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'squash-racket-3',
      name: 'Amazing Squash Racket 3',
      category: 'squash',
      manufacturer: 'prince',
      price: 1127,
      oldPrice: null,
      age: 'adult',
      color: ['black', 'white'],
      stars: 5,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: true,
      saleOff: false,
      source: '/images/racket/squash/squash-racket-3.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'squash-racket-4',
      name: 'Light Squash Racket 4',
      category: 'squash',
      manufacturer: 'head',
      price: 1191,
      oldPrice: 1390,
      age: 'adult',
      color: ['green'],
      stars: 3,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: true,
      source: '/images/racket/squash/squash-racket-4.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'squash-racket-5',
      name: 'Heavy Squash Racket 5',
      category: 'squash',
      manufacturer: 'yonex',
      price: 1394,
      oldPrice: null,
      age: 'adult',
      color: ['blue'],
      stars: 4,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/squash/squash-racket-5.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'squash-racket-6',
      name: 'Pro Squash Racket 6',
      category: 'squash',
      manufacturer: 'wilson',
      price: 1125,
      oldPrice: null,
      age: 'child',
      color: ['red', 'yellow'],
      stars: 2,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/squash/squash-racket-6.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'squash-racket-7',
      name: 'Light Squash Racket 7',
      category: 'squash',
      manufacturer: 'prince',
      price: 767,
      oldPrice: null,
      age: 'adult',
      color: ['blue', 'red'],
      stars: 4,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/squash/squash-racket-7.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'squash-racket-8',
      name: 'Pro Squash Racket 8',
      category: 'squash',
      manufacturer: 'head',
      price: 1181,
      oldPrice: null,
      age: 'adult',
      color: ['white', 'blue'],
      stars: 5,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/squash/squash-racket-8.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'squash-racket-9',
      name: 'Heavy Squash Racket 9',
      category: 'squash',
      manufacturer: 'yonex',
      price: 1312,
      oldPrice: null,
      age: 'adult',
      color: ['blue'],
      stars: 3,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/squash/squash-racket-9.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'squash-racket-10',
      name: 'Light Squash Racket 10',
      category: 'squash',
      manufacturer: 'wilson',
      price: 732,
      oldPrice: null,
      age: 'adult',
      color: ['green'],
      stars: 2,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/squash/squash-racket-10.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'squash-racket-11',
      name: 'Amazing Squash Racket 11',
      category: 'squash',
      manufacturer: 'wilson',
      price: 1199,
      oldPrice: null,
      age: 'adult',
      color: ['green', 'yellow'],
      stars: 2,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/squash/squash-racket-11.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'squash-racket-12',
      name: 'Light Squash Racket 12',
      category: 'squash',
      manufacturer: 'prince',
      price: 1100,
      oldPrice: null,
      age: 'adult',
      color: ['white', 'blue', 'red'],
      stars: 4,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/squash/squash-racket-12.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'squash-racket-13',
      name: 'Pro Squash Racket 13',
      category: 'squash',
      manufacturer: 'yonex',
      price: 1130,
      oldPrice: null,
      age: 'adult',
      color: ['black', 'green', 'white'],
      stars: 5,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/squash/squash-racket-13.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'squash-racket-14',
      name: 'Amateur Squash Racket 14',
      category: 'squash',
      manufacturer: 'head',
      price: 983,
      oldPrice: 1400,
      age: 'adult',
      color: ['yellow'],
      stars: 3,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: true,
      source: '/images/racket/squash/squash-racket-14.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'squash-racket-15',
      name: 'Heavy Squash Racket 15',
      category: 'squash',
      manufacturer: 'babolat',
      price: 1390,
      oldPrice: 1950,
      age: 'adult',
      color: ['black', 'green'],
      stars: 4,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: true,
      source: '/images/racket/squash/squash-racket-15.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'squash-racket-16',
      name: 'Pro Squash Racket 16',
      category: 'squash',
      manufacturer: 'wilson',
      price: 1139,
      oldPrice: null,
      age: 'adult',
      color: ['blue', 'white'],
      stars: 2,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/squash/squash-racket-16.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'squash-racket-17',
      name: 'Heavy Squash Racket 17',
      category: 'squash',
      manufacturer: 'yonex',
      price: 1074,
      oldPrice: null,
      age: 'adult',
      color: ['red', 'green'],
      stars: 4,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/squash/squash-racket-17.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'squash-racket-18',
      name: 'Amazing Squash Racket 18',
      category: 'squash',
      manufacturer: 'prince',
      price: 1231,
      oldPrice: null,
      age: 'child',
      color: ['yellow', 'white'],
      stars: 3,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/squash/squash-racket-18.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'squash-racket-19',
      name: 'Pro Squash Racket 19',
      category: 'squash',
      manufacturer: 'yonex',
      price: 600,
      oldPrice: null,
      age: 'adult',
      color: ['blue', 'white'],
      stars: 5,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/squash/squash-racket-19.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'squash-racket-20',
      name: 'Light Squash Racket 20',
      category: 'squash',
      manufacturer: 'babolat',
      price: 1315,
      oldPrice: null,
      age: 'child',
      color: ['yellow', 'green'],
      stars: 1,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/squash/squash-racket-20.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'squash-racket-21',
      name: 'Pro Squash Racket 21',
      category: 'squash',
      manufacturer: 'wilson',
      price: 1022,
      oldPrice: null,
      age: 'adult',
      color: ['blue'],
      stars: 4,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/squash/squash-racket-21.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'squash-racket-22',
      name: 'Amateur Squash Racket 22',
      category: 'squash',
      manufacturer: 'prince',
      price: 1421,
      oldPrice: 1838,
      age: 'child',
      color: ['black', 'red'],
      stars: 2,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: true,
      source: '/images/racket/squash/squash-racket-22.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'squash-racket-23',
      name: 'Light Squash Racket 23',
      category: 'squash',
      manufacturer: 'yonex',
      price: 1206,
      oldPrice: null,
      age: 'adult',
      color: ['yellow'],
      stars: 5,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/squash/squash-racket-23.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'squash-racket-24',
      name: 'Heavy Squash Racket 24',
      category: 'squash',
      manufacturer: 'wilson',
      price: 1089,
      oldPrice: null,
      age: 'child',
      color: ['green'],
      stars: 3,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/squash/squash-racket-24.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'squash-racket-25',
      name: 'Pro Squash Racket 25',
      category: 'squash',
      manufacturer: 'head',
      price: 649,
      oldPrice: null,
      age: 'child',
      color: ['red', 'green'],
      stars: 2,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/squash/squash-racket-25.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'padel-racket-1',
      name: 'Amazing Padel Racket 1',
      category: 'padel',
      manufacturer: 'wilson',
      price: 932,
      oldPrice: null,
      age: 'adult',
      color: ['green', 'black'],
      stars: 5,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/padel/padel-racket-1.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'padel-racket-2',
      name: 'Amateur Padel Racket 2',
      category: 'padel',
      manufacturer: 'yonex',
      price: 1201,
      oldPrice: null,
      age: 'adult',
      color: ['red', 'yellow'],
      stars: 2,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/padel/padel-racket-2.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'padel-racket-3',
      name: 'Light Padel Racket 3',
      category: 'padel',
      manufacturer: 'babolat',
      price: 1389,
      oldPrice: 1690,
      age: 'child',
      color: ['blue'],
      stars: 4,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: true,
      source: '/images/racket/padel/padel-racket-3.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'padel-racket-4',
      name: 'Pro Padel Racket 4',
      category: 'padel',
      manufacturer: 'head',
      price: 1049,
      oldPrice: null,
      age: 'adult',
      color: ['white', 'black'],
      stars: 3,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/padel/padel-racket-4.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'padel-racket-5',
      name: 'Heavy Padel Racket 5',
      category: 'padel',
      manufacturer: 'prince',
      price: 1323,
      oldPrice: 1745,
      age: 'child',
      color: ['black'],
      stars: 2,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: true,
      source: '/images/racket/padel/padel-racket-5.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'padel-racket-6',
      name: 'Amateur Padel Racket 6',
      category: 'padel',
      manufacturer: 'wilson',
      price: 1015,
      oldPrice: null,
      age: 'adult',
      color: ['black'],
      stars: 2,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/padel/padel-racket-6.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'padel-racket-7',
      name: 'Heavy Padel Racket 7',
      category: 'padel',
      manufacturer: 'babolat',
      price: 1317,
      oldPrice: 1867,
      age: 'child',
      color: ['red', 'white'],
      stars: 3,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: true,
      source: '/images/racket/padel/padel-racket-7.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'padel-racket-8',
      name: 'Light Padel Racket 8',
      category: 'padel',
      manufacturer: 'yonex',
      price: 1199,
      oldPrice: null,
      age: 'adult',
      color: ['yellow', 'blue'],
      stars: 4,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: true,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/padel/padel-racket-8.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'padel-racket-9',
      name: 'Amazing Padel Racket 9',
      category: 'padel',
      manufacturer: 'head',
      price: 1416,
      oldPrice: null,
      age: 'child',
      color: ['blue'],
      stars: 2,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/padel/padel-racket-9.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'padel-racket-10',
      name: 'Pro Padel Racket 10',
      category: 'padel',
      manufacturer: 'prince',
      price: 1091,
      oldPrice: null,
      age: 'child',
      color: ['green'],
      stars: 3,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/padel/padel-racket-10.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'padel-racket-11',
      name: 'Heavy Padel Racket 11',
      category: 'padel',
      manufacturer: 'yonex',
      price: 1296,
      oldPrice: null,
      age: 'child',
      color: ['white'],
      stars: 5,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/padel/padel-racket-11.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'padel-racket-12',
      name: 'Pro Padel Racket 12',
      category: 'padel',
      manufacturer: 'head',
      price: 1184,
      oldPrice: 1674,
      age: 'adult',
      color: ['green', 'white'],
      stars: 4,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: true,
      source: '/images/racket/padel/padel-racket-12.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'padel-racket-13',
      name: 'Amateur Padel Racket 13',
      category: 'padel',
      manufacturer: 'prince',
      price: 1071,
      oldPrice: null,
      age: 'adult',
      color: ['black', 'white'],
      stars: 3,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/padel/padel-racket-13.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'padel-racket-14',
      name: 'Light Padel Racket 14',
      category: 'padel',
      manufacturer: 'babolat',
      price: 845,
      oldPrice: 1146,
      age: 'child',
      color: ['black', 'green'],
      stars: 4,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: true,
      source: '/images/racket/padel/padel-racket-14.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'padel-racket-15',
      name: 'Amazing Padel Racket 15',
      category: 'padel',
      manufacturer: 'wilson',
      price: 878,
      oldPrice: null,
      age: 'adult',
      color: ['yellow', 'green'],
      stars: 3,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/padel/padel-racket-15.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'padel-racket-16',
      name: 'Pro Padel Racket 16',
      category: 'padel',
      manufacturer: 'wilson',
      price: 831,
      oldPrice: null,
      age: 'adult',
      color: ['black', 'green'],
      stars: 3,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/padel/padel-racket-16.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'padel-racket-17',
      name: 'Amateur Padel Racket 17',
      category: 'padel',
      manufacturer: 'prince',
      price: 1107,
      oldPrice: 1569,
      age: 'adult',
      color: ['white'],
      stars: 4,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: true,
      source: '/images/racket/padel/padel-racket-17.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'padel-racket-18',
      name: 'Heavy Padel Racket 18',
      category: 'padel',
      manufacturer: 'yonex',
      price: 707,
      oldPrice: 1720,
      age: 'adult',
      color: ['yellow', 'green'],
      stars: 3,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: true,
      source: '/images/racket/padel/padel-racket-18.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'padel-racket-19',
      name: 'Amazing Padel Racket 19',
      category: 'padel',
      manufacturer: 'head',
      price: 1265,
      oldPrice: null,
      age: 'adult',
      color: ['blue', 'white'],
      stars: 4,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/padel/padel-racket-19.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'padel-racket-20',
      name: 'Pro Padel Racket 20',
      category: 'padel',
      manufacturer: 'wilson',
      price: 1383,
      oldPrice: null,
      age: 'adult',
      color: ['red', 'white'],
      stars: 5,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: true,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/padel/padel-racket-20.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'padel-racket-21',
      name: 'Pro Padel Racket 21',
      category: 'padel',
      manufacturer: 'wilson',
      price: 849,
      oldPrice: null,
      age: 'adult',
      color: ['black', 'red'],
      stars: 3,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/padel/padel-racket-21.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'padel-racket-22',
      name: 'Amazing Padel Racket 22',
      category: 'padel',
      manufacturer: 'yonex',
      price: 1429,
      oldPrice: null,
      age: 'adult',
      color: ['white', 'red'],
      stars: 5,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/padel/padel-racket-22.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'padel-racket-23',
      name: 'Light Padel Racket 23',
      category: 'padel',
      manufacturer: 'head',
      price: 1249,
      oldPrice: null,
      age: 'adult',
      color: ['green', 'yellow'],
      stars: 4,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/padel/padel-racket-23.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'padel-racket-24',
      name: 'Amateur Padel Racket 24',
      category: 'padel',
      manufacturer: 'prince',
      price: 1299,
      oldPrice: null,
      age: 'adult',
      color: ['blue', 'white'],
      stars: 4,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/padel/padel-racket-24.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'padel-racket-25',
      name: 'Heavy Padel Racket 25',
      category: 'padel',
      manufacturer: 'babolat',
      price: 1379,
      oldPrice: null,
      age: 'adult',
      color: ['black', 'yellow'],
      stars: 3,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/padel/padel-racket-25.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'badminton-racket-1',
      name: 'Amazing Badminton Racket 1',
      category: 'badminton',
      manufacturer: 'wilson',
      price: 1169,
      oldPrice: null,
      age: 'child',
      color: ['green', 'yellow'],
      stars: 4,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/badminton/badminton-racket-1.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'badminton-racket-2',
      name: 'Pro Badminton Racket 2',
      category: 'badminton',
      manufacturer: 'head',
      price: 870,
      oldPrice: null,
      age: 'adult',
      color: ['yellow'],
      stars: 3,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/badminton/badminton-racket-2.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'badminton-racket-3',
      name: 'Heavy Badminton Racket 3',
      category: 'badminton',
      manufacturer: 'babolat',
      price: 1186,
      oldPrice: null,
      age: 'child',
      color: ['blue', 'red'],
      stars: 4,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/badminton/badminton-racket-3.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'badminton-racket-4',
      name: 'Amazing Badminton Racket 4',
      category: 'badminton',
      manufacturer: 'wilson',
      price: 1418,
      oldPrice: null,
      age: 'adult',
      color: ['yellow', 'blue'],
      stars: 4,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/badminton/badminton-racket-4.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'badminton-racket-5',
      name: 'Light Badminton Racket 5',
      category: 'badminton',
      manufacturer: 'prince',
      price: 962,
      oldPrice: null,
      age: 'adult',
      color: ['green', 'red'],
      stars: 3,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/badminton/badminton-racket-5.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'badminton-racket-6',
      name: 'Amazing Badminton Racket 6',
      category: 'badminton',
      manufacturer: 'prince',
      price: 1274,
      oldPrice: 1194,
      age: 'child',
      color: ['yellow'],
      stars: 2,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: true,
      source: '/images/racket/badminton/badminton-racket-6.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'badminton-racket-7',
      name: 'Light Badminton Racket 7',
      category: 'badminton',
      manufacturer: 'yonex',
      price: 1238,
      oldPrice: null,
      age: 'adult',
      color: ['white', 'yellow'],
      stars: 2,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/badminton/badminton-racket-7.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'badminton-racket-8',
      name: 'Heavy Badminton Racket 8',
      category: 'badminton',
      manufacturer: 'head',
      price: 1291,
      oldPrice: 1650,
      age: 'adult',
      color: ['red'],
      stars: 5,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: true,
      source: '/images/racket/badminton/badminton-racket-8.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'badminton-racket-9',
      name: 'Amateur Badminton Racket 9',
      category: 'badminton',
      manufacturer: 'prince',
      price: 1303,
      oldPrice: null,
      age: 'adult',
      color: ['black', 'red'],
      stars: 3,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/badminton/badminton-racket-9.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'badminton-racket-10',
      name: 'Pro Badminton Racket 10',
      category: 'badminton',
      manufacturer: 'babolat',
      price: 876,
      oldPrice: 1377,
      age: 'child',
      color: ['green'],
      stars: 2,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: true,
      source: '/images/racket/badminton/badminton-racket-10.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'badminton-racket-11',
      name: 'Light Badminton Racket 11',
      category: 'badminton',
      manufacturer: 'yonex',
      price: 1438,
      oldPrice: null,
      age: 'child',
      color: ['red'],
      stars: 3,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/badminton/badminton-racket-11.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'badminton-racket-12',
      name: 'Heavy Badminton Racket 12',
      category: 'badminton',
      manufacturer: 'head',
      price: 1142,
      oldPrice: 1498,
      age: 'child',
      color: ['yellow', 'green'],
      stars: 1,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: true,
      source: '/images/racket/badminton/badminton-racket-12.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'badminton-racket-13',
      name: 'Pro Badminton Racket 13',
      category: 'badminton',
      manufacturer: 'prince',
      price: 1384,
      oldPrice: null,
      age: 'adult',
      color: ['black'],
      stars: 4,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/badminton/badminton-racket-13.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'badminton-racket-14',
      name: 'Pro Badminton Racket 14',
      category: 'badminton',
      manufacturer: 'wilson',
      price: 891,
      oldPrice: null,
      age: 'adult',
      color: ['white', 'green'],
      stars: 3,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/badminton/badminton-racket-14.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'badminton-racket-15',
      name: 'Amazing Badminton Racket 15',
      category: 'badminton',
      manufacturer: 'yonex',
      price: 868,
      oldPrice: null,
      age: 'child',
      color: ['yellow', 'red'],
      stars: 5,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/badminton/badminton-racket-15.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'badminton-racket-16',
      name: 'Light Badminton Racket 16',
      category: 'badminton',
      manufacturer: 'wilson',
      price: 1203,
      oldPrice: null,
      age: 'adult',
      color: ['red'],
      stars: 2,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/badminton/badminton-racket-16.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'badminton-racket-17',
      name: 'Pro Badminton Racket 17',
      category: 'badminton',
      manufacturer: 'head',
      price: 1267,
      oldPrice: null,
      age: 'child',
      color: ['green'],
      stars: 3,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/badminton/badminton-racket-17.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'badminton-racket-18',
      name: 'Heavy Badminton Racket 18',
      category: 'badminton',
      manufacturer: 'prince',
      price: 929,
      oldPrice: 1344,
      age: 'child',
      color: ['yellow', 'blue'],
      stars: 4,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: true,
      source: '/images/racket/badminton/badminton-racket-18.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'badminton-racket-19',
      name: 'Amazing Badminton Racket 19',
      category: 'badminton',
      manufacturer: 'yonex',
      price: 1343,
      oldPrice: null,
      age: 'adult',
      color: ['green', 'red'],
      stars: 5,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: true,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/badminton/badminton-racket-19.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'badminton-racket-20',
      name: 'Pro Badminton Racket 20',
      category: 'badminton',
      manufacturer: 'babolat',
      price: 1095,
      oldPrice: null,
      age: 'adult',
      color: ['white', 'yellow'],
      stars: 3,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/badminton/badminton-racket-20.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'badminton-racket-21',
      name: 'Heavy Badminton Racket 21',
      category: 'badminton',
      manufacturer: 'yonex',
      price: 1420,
      oldPrice: null,
      age: 'adult',
      color: ['blue', 'white'],
      stars: 2,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/badminton/badminton-racket-21.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'badminton-racket-22',
      name: 'Pro Badminton Racket 22',
      category: 'badminton',
      manufacturer: 'yonex',
      price: 1330,
      oldPrice: 1730,
      age: 'adult',
      color: ['green'],
      stars: 4,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: true,
      source: '/images/racket/badminton/badminton-racket-22.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'badminton-racket-23',
      name: 'Amateur Badminton Racket 23',
      category: 'badminton',
      manufacturer: 'prince',
      price: 613,
      oldPrice: null,
      age: 'child',
      color: ['yellow'],
      stars: 1,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/badminton/badminton-racket-23.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'badminton-racket-24',
      name: 'Light Badminton Racket 24',
      category: 'badminton',
      manufacturer: 'head',
      price: 941,
      oldPrice: null,
      age: 'adult',
      color: ['red', 'yellow'],
      stars: 3,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/badminton/badminton-racket-24.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'badminton-racket-25',
      name: 'Pro Badminton Racket 25',
      category: 'badminton',
      manufacturer: 'wilson',
      price: 950,
      oldPrice: null,
      age: 'adult',
      color: ['green'],
      stars: 5,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/badminton/badminton-racket-25.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tableTenis-racket-1',
      name: 'Amazing Table Tenis Racket 1',
      category: 'tableTenis',
      manufacturer: 'yonex',
      price: 1031,
      oldPrice: 1609,
      age: 'adult',
      color: ['green'],
      stars: 2,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: true,
      source: '/images/racket/tableTenis/tableTenis-racket-1.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tableTenis-racket-2',
      name: 'Amateur Table Tenis Racket 2',
      category: 'tableTenis',
      manufacturer: 'wilson',
      price: 677,
      oldPrice: null,
      age: 'adult',
      color: ['red'],
      stars: 2,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/tableTenis/tableTenis-racket-2.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tableTenis-racket-3',
      name: 'Heavy Table Tenis Racket 3',
      category: 'tableTenis',
      manufacturer: 'yonex',
      price: 634,
      oldPrice: 1208,
      age: 'adult',
      color: ['blue', 'green'],
      stars: 4,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: true,
      source: '/images/racket/tableTenis/tableTenis-racket-3.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tableTenis-racket-4',
      name: 'Light Table Tenis Racket 4',
      category: 'tableTenis',
      manufacturer: 'head',
      price: 607,
      oldPrice: 876,
      age: 'adult',
      color: ['yellow'],
      stars: 5,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: true,
      topSeller: true,
      saleOff: true,
      source: '/images/racket/tableTenis/tableTenis-racket-4.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tableTenis-racket-5',
      name: 'Pro Table Tenis Racket 5',
      category: 'tableTenis',
      manufacturer: 'yonex',
      price: 710,
      oldPrice: null,
      age: 'adult',
      color: ['green', 'yellow'],
      stars: 4,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/tableTenis/tableTenis-racket-5.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tableTenis-racket-6',
      name: 'Pro Table Tennis Table 6',
      category: 'tableTenis',
      manufacturer: 'babolat',
      price: 1148,
      oldPrice: null,
      age: 'adult',
      color: ['black', 'green'],
      stars: 5,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/tableTenis/tableTenis-racket-6.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tableTenis-racket-7',
      name: 'Amateur Table Tennis Racket 7',
      category: 'tableTenis',
      manufacturer: 'head',
      price: 1145,
      oldPrice: null,
      age: 'child',
      color: ['red'],
      stars: 2,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/tableTenis/tableTenis-racket-7.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tableTenis-racket-8',
      name: 'Amazing Table Tennis Racket 8',
      category: 'tableTenis',
      manufacturer: 'wilson',
      price: 845,
      oldPrice: null,
      age: 'adult',
      color: ['yellow', 'white'],
      stars: 3,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/tableTenis/tableTenis-racket-8.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tableTenis-racket-9',
      name: 'Light Table Tennis Racket 9',
      category: 'tableTenis',
      manufacturer: 'prince',
      price: 986,
      oldPrice: 1644,
      age: 'child',
      color: ['blue'],
      stars: 4,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: true,
      source: '/images/racket/tableTenis/tableTenis-racket-9.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tableTenis-racket-10',
      name: 'Heavy Table Tennis Racket 10',
      category: 'tableTenis',
      manufacturer: 'yonex',
      price: 1123,
      oldPrice: null,
      age: 'adult',
      color: ['green', 'white'],
      stars: 5,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/tableTenis/tableTenis-racket-10.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tableTenis-racket-11',
      name: 'Pro TableTenis Racket 11',
      category: 'tableTenis',
      manufacturer: 'wilson',
      price: 1222,
      oldPrice: null,
      age: 'adult',
      color: ['blue', 'white'],
      stars: 4,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/tableTenis/tableTenis-racket-11.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tableTenis-racket-12',
      name: 'Amateur TableTenis Racket 12',
      category: 'tableTenis',
      manufacturer: 'yonex',
      price: 1201,
      oldPrice: null,
      age: 'adult',
      color: ['red', 'white'],
      stars: 1,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/tableTenis/tableTenis-racket-12.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tableTenis-racket-13',
      name: 'Amazing TableTenis Racket 13',
      category: 'tableTenis',
      manufacturer: 'prince',
      price: 625,
      oldPrice: 1092,
      age: 'adult',
      color: ['black', 'green'],
      stars: 3,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: true,
      source: '/images/racket/tableTenis/tableTenis-racket-13.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tableTenis-racket-14',
      name: 'Light TableTenis Racket 14',
      category: 'tableTenis',
      manufacturer: 'head',
      price: 638,
      oldPrice: null,
      age: 'child',
      color: ['blue'],
      stars: 5,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/tableTenis/tableTenis-racket-14.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tableTenis-racket-15',
      name: 'Heavy TableTenis Racket 15',
      category: 'tableTenis',
      manufacturer: 'babolat',
      price: 802,
      oldPrice: null,
      age: 'adult',
      color: ['white', 'red'],
      stars: 4,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/tableTenis/tableTenis-racket-15.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tableTenis-racket-16',
      name: 'Pro Table Tennis Racket 16',
      category: 'tableTenis',
      manufacturer: 'head',
      price: 1099,
      oldPrice: 1550,
      age: 'adult',
      color: ['red', 'black'],
      stars: 3,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: true,
      source: '/images/racket/tableTenis/tableTenis-racket-16.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tableTenis-racket-17',
      name: 'Amateur Table Tennis Racket 17',
      category: 'tableTenis',
      manufacturer: 'yonex',
      price: 999,
      oldPrice: null,
      age: 'adult',
      color: ['blue', 'green'],
      stars: 4,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/tableTenis/tableTenis-racket-17.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tableTenis-racket-18',
      name: 'Amazing Table Tennis Racket 18',
      category: 'tableTenis',
      manufacturer: 'prince',
      price: 1399,
      oldPrice: 1970,
      age: 'adult',
      color: ['yellow', 'black'],
      stars: 5,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: true,
      saleOff: true,
      source: '/images/racket/tableTenis/tableTenis-racket-18.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tableTenis-racket-19',
      name: 'Light Table Tennis Racket 19',
      category: 'tableTenis',
      manufacturer: 'wilson',
      price: 899,
      oldPrice: null,
      age: 'child',
      color: ['white', 'red'],
      stars: 3,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: true,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/tableTenis/tableTenis-racket-19.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tableTenis-racket-20',
      name: 'Heavy Table Tennis Racket 20',
      category: 'tableTenis',
      manufacturer: 'babolat',
      price: 1299,
      oldPrice: null,
      age: 'adult',
      color: ['black', 'green'],
      stars: 4,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: true,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/tableTenis/tableTenis-racket-20.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tableTenis-racket-21',
      name: 'Pro Table Tennis Racket 21',
      category: 'tableTenis',
      manufacturer: 'babolat',
      price: 1264,
      oldPrice: null,
      age: 'adult',
      color: ['blue'],
      stars: 3,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/tableTenis/tableTenis-racket-21.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tableTenis-racket-22',
      name: 'Amateur Table Tennis Racket 22',
      category: 'tableTenis',
      manufacturer: 'head',
      price: 1053,
      oldPrice: null,
      age: 'adult',
      color: ['red', 'green'],
      stars: 5,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/tableTenis/tableTenis-racket-22.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tableTenis-racket-23',
      name: 'Amazing Table Tennis Racket 23',
      category: 'tableTenis',
      manufacturer: 'prince',
      price: 1391,
      oldPrice: null,
      age: 'adult',
      color: ['blue', 'white'],
      stars: 4,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/tableTenis/tableTenis-racket-23.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tableTenis-racket-24',
      name: 'Light Table Tennis Racket 24',
      category: 'tableTenis',
      manufacturer: 'yonex',
      price: 1191,
      oldPrice: null,
      age: 'adult',
      color: ['green'],
      stars: 2,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/tableTenis/tableTenis-racket-24.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
    {
      id: 'tableTenis-racket-25',
      name: 'Heavy Table Tennis Racket 25',
      category: 'tableTenis',
      manufacturer: 'prince',
      price: 1149,
      oldPrice: null,
      age: 'adult',
      color: ['yellow'],
      stars: 4,
      newProduct: true,
      myStars: null,
      promo: 'sale',
      favourite: false,
      compare: false,
      featured: false,
      topSeller: false,
      saleOff: false,
      source: '/images/racket/tableTenis/tableTenis-racket-25.webp',
      overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      quantity: 1,
    },
  ],
  cart: {
    products: [
      {
        id: 'tenis-racket-1',
        name: 'Pro Tenis Racket 1',
        price: 1038,
        source: '/images/racket/tenis/tenis-racket-1.webp',
        overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
        quantity: 1,
        amount: 1,
      },
    ],
    coupons: [
      { id: 'bluemonday', type: 'freeDelivery' },
      { id: 'blackfriday', type: 'discount', value: 0.5 },
    ],
  },
  brands: [
    { id: 1, source: '/images/brands/brand 1.png', brandName: 'brand 1' },
    { id: 2, source: '/images/brands/brand 2.png', brandName: 'brand 2' },
    { id: 3, source: '/images/brands/brand 3.png', brandName: 'brand 3' },
    { id: 4, source: '/images/brands/brand 4.png', brandName: 'brand 4' },
    { id: 5, source: '/images/brands/brand 5.png', brandName: 'brand 5' },
    { id: 6, source: '/images/brands/brand 6.png', brandName: 'brand 6' },
    { id: 7, source: '/images/brands/brand 7.png', brandName: 'brand 7' },
    { id: 8, source: '/images/brands/brand 8.png', brandName: 'brand 8' },
    { id: 9, source: '/images/brands/brand 9.png', brandName: 'brand 9' },
    { id: 10, source: '/images/brands/brand 10.png', brandName: 'brand 10' },
  ],
  viewportMode: '',
  feedbacks: [
    {
      id: 0,
      author: 'Luctus Lacus',
      status: 'Client',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    },
    {
      id: 1,
      author: 'Donec Ultrices',
      status: 'Supplier',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    },
    {
      id: 2,
      author: 'Praesent Pulvinar',
      status: 'Designer',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    },
  ],
  blogPosts: [
    {
      id: 1,
      date: '01 MAR 2023',
      title: 'Lorem ipsum',
      text:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      source: '/images/blog/blog-1.webp',
      author: 'admin',
      category: 'Just usual',
    },
    {
      id: 2,
      date: '02 MAR 2023',
      title: 'Lorem ipsum',
      text:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      source: '/images/blog/blog-2.webp',
      author: 'admin',
      category: 'Just usual',
    },
    {
      id: 3,
      date: '03 MAR 2023',
      title: 'Lorem ipsum',
      text:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in.',
      source: '/images/blog/blog-3.webp',
      author: 'admin',
      category: 'Just usual',
    },
    {
      id: 4,
      date: '02 MAR 2023',
      title: 'Lorem ipsum',
      text:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      source: '/images/blog/blog-4.webp',
      author: 'admin',
      category: 'Just usual',
    },
    {
      id: 5,
      date: '03 MAR 2023',
      title: 'Lorem ipsum',
      text:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper ultrices dolor, quis commodo sem porttitor in.',
      source: '/images/blog/blog-5.webp',
      author: 'admin',
      category: 'Just usual',
    },
  ],
  promotion: {
    firstImage: './images/racket/tenis/tenis-racket-21.webp',
    firstAltName: 'tenis-racket',
    firstTitle: 'Tenis Rackets',
    firstTitleStrong: 'head',
    firstDiscountBox: '-15%',
    secondImage: './images/racket/badminton/badminton-racket-19.webp',
    secondAltName: 'badminton-racket',
    secondTitleStrong: 'Badminton Rackets',
    secondSubtitle: 'collection',
    secondPrice: 'up to -25%',
    thirdImage: './images/racket/squash/squash-racket-17.webp',
    thirdAltName: 'squash-racket',
    thirdTitleStrong: 'special',
    thirdTitle: 'collection',
    thirdSubtitle: 'save up to 45% on squash rackets',
  },
  searchText: '',
  currency: { name: 'USD', multiplier: 1, sign: '$' },
  productFilters: [],
};
export default initialState;
